# Generated by Django 5.1.4 on 2025-01-13 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_college_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='department',
        ),
    ]
