# Generated by Django 5.1.4 on 2025-01-13 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_college_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50, null=True)),
                ('option1', models.CharField(max_length=10, null=True)),
                ('option2', models.CharField(max_length=10, null=True)),
                ('option3', models.CharField(max_length=10, null=True)),
                ('option4', models.CharField(max_length=10, null=True)),
                ('answer', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.IntegerField()),
                ('two', models.IntegerField(blank=True, null=True)),
                ('total_sum', models.IntegerField(default=0)),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
            ],
        ),
    ]
