# Generated by Django 5.1.3 on 2025-01-13 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('duration', models.CharField(max_length=50, null=True)),
                ('fees', models.CharField(max_length=50, null=True)),
                ('details', models.CharField(max_length=100, null=True)),
                ('gpa', models.FloatField(null=True)),
                ('clg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.college')),
            ],
        ),
    ]
