# Generated by Django 5.1.3 on 2025-01-14 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
    ]
