# Generated by Django 5.1.3 on 2025-01-15 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_financer_delete_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('provider', models.CharField(max_length=100, null=True)),
                ('interest_rate', models.CharField(max_length=100, null=True)),
                ('max_amount', models.CharField(max_length=100, null=True)),
                ('tenure_years', models.CharField(max_length=100, null=True)),
                ('eligibile_gpa', models.CharField(max_length=100, null=True)),
                ('details', models.CharField(max_length=100, null=True)),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.college')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('fin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.financer')),
            ],
        ),
    ]
