# Generated by Django 5.1.3 on 2025-01-15 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.mentor'),
        ),
    ]
