# Generated by Django 5.1.3 on 2025-01-15 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPreparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField(null=True)),
                ('pdf', models.FileField(null=True, upload_to='file')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mentor')),
            ],
        ),
    ]
