# Generated by Django 5.1.3 on 2025-01-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_interviewpreparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.FileField(null=True, upload_to='file'),
        ),
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
