# Generated by Django 5.1.3 on 2025-01-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_student_image_student_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='image',
            field=models.FileField(null=True, upload_to='file'),
        ),
    ]
